version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    networks:
      - ratingus-network
    ports:
      - "3000:3000"

networks:
  ratingus-network:
    external: true