version: "3.8"

services:
  frontend:
    image: ghcr.io/ratingus/ratingus-web:latest
    container_name: frontend
    restart: always
    networks:
      - ratingus-network
    ports:
      - "3000:3000"
  storybook:
    image: ghcr.io/ratingus/ratingus-web-storybook:latest
    container_name: storybook
    restart: always
    networks:
      - ratingus-network
    ports:
      - "6006:80"

networks:
  ratingus-network:
    external: true
