---

- name: Update Docker Compose containers
  hosts: ratingus
  gather_facts: no
  become: yes

  tasks:
    - name: Recreate services
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
      register: output
